driver: fix: driver/mysql/mysql.go:89:23: undefined: mysql.MySQLWarnings
compilation failed with:
  driver: fix: driver/mysql/mysql.go:89:23: undefined: mysql.MySQLWarnings

MySQLWarnings was removed from the mysql driver
(https://github.com/go-sql-driver/mysql/pull/676), remove it from
migrate